CREATE TABLE File (
    "id" INTEGER NOT NULL PRIMARY KEY,
    "path" TEXT NOT NULL UNIQUE,
    "modifiedTime" INTEGER NOT NULL,
    "permissions" INTEGER
);

CREATE TABLE RegularFile (
    "file_id" INTEGER NOT NULL PRIMARY KEY REFERENCES File("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "size" INTEGER NOT NULL,
    "checksum" BLOB NOT NULL UNIQUE
);

CREATE TABLE SymbolicLink (
    "file_id" INTEGER NOT NULL PRIMARY KEY REFERENCES File("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "target" TEXT NOT NULL
);

CREATE TABLE Directory (
    "file_id" INTEGER NOT NULL PRIMARY KEY REFERENCES File("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ExtendedAttribute (
    "id" INTEGER NOT NULL PRIMARY KEY,
    "file_id" INTEGER NOT NULL REFERENCES File("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "name" TEXT NOT NULL,
    "value" BLOB NOT NULL
);

CREATE TABLE Blob (
    "id" INTEGER NOT NULL PRIMARY KEY,
    "size" INTEGER NOT NULL,
    "checksum" BLOB NOT NULL UNIQUE,
    "data" BLOB NOT NULL
);

CREATE TABLE Block (
    "file_id" INTEGER NOT NULL REFERENCES File("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "blob_id" INTEGER NOT NULL REFERENCES Blob("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "index" INTEGER NOT NULL,
    PRIMARY KEY ("file_id", "blob_id", "index")
);
